apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-master-config
  namespace: redis-ha
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    requirepass redis@HA2024
    masterauth redis@HA2024
    appendonly yes
    appendfsync everysec
    loglevel notice
    protected-mode no
    save 900 1
    save 300 10
    save 60 10000
