# =============================================================================
# ArgoCD Applications
# Aplica com: kubectl apply -f argocd-apps.yaml
# =============================================================================

# --- Manager ---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manager
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: manager
spec:
  project: default
  source:
    repoURL: https://github.com/ViniciusClaudomir/k8s.git
    targetRevision: main
    path: manager
  destination:
    server: https://kubernetes.default.svc
    namespace: manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

# --- revision-proxy ---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: revision-proxy-k8s
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: revision-proxy-k8s
spec:
  project: default
  source:
    repoURL: https://github.com/ViniciusClaudomir/k8s.git
    targetRevision: main
    path: revision-proxy-k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: revision-proxy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

# --- submit ---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: submit
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: submit
spec:
  project: default
  source:
    repoURL: https://github.com/ViniciusClaudomir/k8s.git
    targetRevision: main
    path: submit
  destination:
    server: https://kubernetes.default.svc
    namespace: submit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
