apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: submit
  namespace: submit
spec:
  template:
    metadata:
      name: submit-base
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "4"
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "10s"
    spec:
      containers:
        - name: submit
          image: dev.local/submit:v9
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
              name: http1
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 20
            failureThreshold: 3
